### ISSUE TITLE
Améliorer l'ergonomie générale

### ISSUE THREAD

**Issue by overflorian** [data-osm/frontend#8]
Salut,
Comme promis @JLZIMMERMANN et Karl, je vous fait un retour un peu général sur des questions d'interface utilisateur. On pourra subdiviser en sous-issues plus tard en faisant le tri de ce qui vous intéresse.

Je pense que, par ordre d'importance (plus important en premier), vous devriez :
- faire un beau logo qui reflète les valeurs du projet. Je vois un (A) comme favicon, c'est peut-être une bonne base
- accélérer le temps d'ouverture initial du site
- peaufiner l'interface générale, en respectant bien plus les règles d'ergonomie.
Par exemple :
  - les labels des icônes ne sont pas séparés, on a l'impression que c'est un texte continu.
![image](https://user-images.githubusercontent.com/11553211/95564056-87e28c80-0a1e-11eb-8941-401811dac43f.png)
Peut-être faudrait-il créer des boutons bien séparés ?
  - certains libellés sont coupés :
![image](https://user-images.githubusercontent.com/11553211/95565054-eceab200-0a1f-11eb-9a37-22d334919b75.png)
  - vous avez fait des catégories qui contiennent énormément d'éléments. Il faut faciliter leur affichage.
Par exemple dans la catégorie "commerces" il y a des dizaines de commerces. Je pense qu'il faut revoir le mode de sélection de ces éléments.
  - A quoi servent les boutons "vue passée" et "vue suivante" ?
![image](https://user-images.githubusercontent.com/11553211/95565774-f1639a80-0a20-11eb-9482-2750d593a307.png)
Je n'ai toujours pas compris
  - le bouton "vue générale" ne me paraît pas indispensable
  - lorsque l'on indique un chiffre sur une icône, cela signifie souvent qu'il y a une notification. C'est bizarre d'en mettre un ici :
![image](https://user-images.githubusercontent.com/11553211/95564112-a183d400-0a1e-11eb-84ef-4cd347dbd2e7.png)
  - Pourquoi n'y a-t-il pas d'icône sur le bouton "partager" ?
![image](https://user-images.githubusercontent.com/11553211/95565924-266fed00-0a21-11eb-92df-dc414626133c.png)
Quand on clique dessus, rien ne se passe
  - la légende est toujours vide, pourquoi ?
  - les images des fonds de carte sont toutes ratatinées :
![image](https://user-images.githubusercontent.com/11553211/95564299-e4de4280-0a1e-11eb-99be-df4ad04c251e.png)
  - le bouton "la métropole" me paraît bizarre : 
![image](https://user-images.githubusercontent.com/11553211/95564872-ae54f780-0a1f-11eb-8c3d-60d96d28fa4f.png)
On ne sait pas vraiment ce qu'il indique. Avant de cliquer dessus, je n'avais aucune idée qu'une liste de territoires d'outre-mer allait s'afficher. Peut-être que le label de ce bouton est "territoires d'outre-mer" ou tout simplement "outre-mer"
  - le menu de téléchargement des données ne me paraît pas clair. pourquoi recréer des filtres à cet endroit-là, alors qu'il existe déjà les filtres des catégories de la barre de gauche ? Les filtres de téléchargement devraient se mettre à jour lorsque l'on change la sélection dans le menu. Ils devraient aussi se limiter à la zone géographique trouvée via la barre de recherche du haut.
_Par exemple, je cherche "montrouge" dans la barre de recherche. Je trouve bien cette commune et la sélectionne. Puis je trouve "pharmacie" dans le menu de gauche. Le menu de téléchargement des données devrait à ce moment là proposer le téléchargement des pharmacies de Montrouge._
  - dans le popup, la mention "afficher tout" est sous-lignée 
![image](https://user-images.githubusercontent.com/11553211/95566277-a1d19e80-0a21-11eb-9a86-357e1ad99038.png)
Souligner du texte signifie que c'est un lien hypertexte. Ici cela devrait être un bouton ou mieux, une simple icône.
  - dans le popup, le bouton partager pourrait être remplacé par l’icône de partage
  - sur la carte, vous utilisez les icônes des catégories 
![image](https://user-images.githubusercontent.com/11553211/95566453-dd6c6880-0a21-11eb-8294-330b760aef98.png)
Il serait plus lisible d'utiliser des points ou des pointeurs ou des gouttes.

D'une manière générale, je trouve que l'interface est très surchargée.
Posez-vous la question : quel est le but du site ? Quel est le public qui va le visiter ?
Cela vous aidera à trancher une autre question : que peut-on retirer sur l'interface ? Quels éléments ne sont pas indispensables ?
_Par exemple, les outils pour faire des dessins, est-ce une fonctionnalité indispensable ? Est-ce que l'on a besoin des outils de mesure ? D'altimétrie ? Je n'ai pas la réponse, mais je pense qu'il faut se poser la question._

La hiérarchie des éléments me paraît également à revoir. Si vous décidez que le site est prioritairement fait pour afficher puis télécharger les données d'un calque, alors le bouton "télécharger" ne devrait pas être aussi petit que les autres fonctionnalités :
![image](https://user-images.githubusercontent.com/11553211/95564797-9aa99100-0a1f-11eb-8a1f-f5d55843b880.png)

D'une manière générale, je me sers énormément de toutes les ressources de design de Google sur le site https://material.io à chaque question d'ergonomie sur laquelle je me penche. Je vous conseille également d'installer et d'imiter les applis grand public qui sont très instructives en terme d'ergonomie : Google Maps, Maps.Me mais aussi plein d'applis non-carto. Quand je me pose une question d'ergonomie, j'ouvre souvent une dizaine d'applis pour les comparer. Et puis je fais des mockups qui peuvent être débatus sur github ou entre vous.
_Quelques exemples : https://github.com/osmontrouge/caresteouvert/issues/762 https://github.com/osmontrouge/caresteouvert/issues/449 https://github.com/osmontrouge/caresteouvert/issues/225 https://github.com/osmontrouge/caresteouvert/issues/627_

Sur le site du Material Design, il y a du code informatique / des librairies pour implémenter les comportements et interfaces. Ce n'est donc pas simplement une source d'inspiration mais cela apporte des solutions techniques directement utilisables.
Il y a aussi de superbes exemples sur lesquels je me repose souvent : https://material.io/design/material-studies/about-our-material-studies.html#about-material-studies

A votre dispo pour vous aider à plonger dans l'univers _magique_ du design, si cela vous intéresse.

**Comment by TANK2003** [comment]
Bonjour Florian,
Merci beaucoup pour tes retours constructifs, détaillés et illustrés. Je vais parcourir point pas point et ouvrir des tickets lorsque nécessaire :

- [ ]  **Faire un beau logo qui reflète les valeurs du projet. Je vois un (A) comme favicon, c'est peut-être une bonne base**: On pensait plus a faire un logo-texte comme celui qui sur le bandeau haut du site, au coin gauche.  Le (A) sera enlevé, c'est juste un favicon par défaut

- [x] **Accélérer le temps d'ouverture initial du site**: la latence est du au fait qu'il faut télécharger la limite géographique de la France et des DOM-TOM. J'ai fait une simplification de géométrie trie pour alleger le poids du fichier. On est passé a un chargement de la page en deux secondes.

- [ ] **les labels des icônes ne sont pas séparés, on a l'impression que c'est un texte continu.** : c'est un problème assez complexe car il faut pouvoir trouver des mots pas long pour des couches. Pour ca je pense agrandir le volet de gauche afin d'avoir plus d'espaces et augmenter les intervalles entre les textes. Pour cela, je crée un ticket #10 

- [ ] **vous avez fait des catégories qui contiennent énormément d'éléments. Il faut faciliter leur affichage... [exemple, le groupe commerce]**: Il y'a 365 couches, ca devient de plus en plus difficile de les gérer effectivement. Le but du portail étant de montrer jusqu'ou peut aller la carto sur OSM, on voudrait pas diminuer les couches. @JLZIMMERMANN avait pensé à introduire une notion de profil dans le portail. Il s'agira de filtrer les données en fonction du profil qu'on aura choisi en entrée (santé, éducation, administration territorial, etc...). Idée a beaucoup creuser. Si intérêt, je peux ouvrir un ticket dédié 

- [x] **A quoi servent les boutons "vue passée" et "vue suivante" ?**: Pour un redo/undo de la navigation sur la carte. Plus qu'on est dans une optique de simplification du portail, j'opte pour l'enlever #11

- [x] **le bouton "vue générale" ne me paraît pas indispensable**: pour ceux qui n'ont pas de souris avec une molette ou qui utilise juste le trackpad du laptop, ca peut être  agréable de revenir sur la vue général  en un seul clic

- [x] **lorsque l'on indique un chiffre sur une icône, cela signifie souvent qu'il y a une notification. C'est bizarre d'en mettre un ici** Dans la même démarche de simplicité, j'opte pour son retrait #13

- [ ] **Pourquoi n'y a-t-il pas d'icône sur le bouton "partager" ?**: c'est bizarre, il apparaît bien sur chrome, safari et Firefox. Je remarque qu'elle apparait non plus dans la fiche descriptive d'une entité. tu utilises quelle navigateur stp ?

- [ ] **les images des fonds de carte sont toutes ratatinées** : j'ouvre un ticket la dessus, il a assez duré ce problème #12

- [x] **le bouton "la métropole" me paraît bizarre** exact, mais pas place pour un label. De plus au clic on comprend immédiatement de quoi il s'agit. Donc j'opte plus pour laisser comme ca, sauf si tu as une idée ou une piste de reflexion ?

- [x] **le menu de téléchargement des données ne me paraît pas clair.** merci, c'est bien clair. j'ouvre un ticket pour cela #14

- [ ] **dans le popup, la mention "afficher tout" est sous-lignée**: une icône en forme de flèche descendante fera l'affaire #15

- [x] **sur la carte, vous utilisez les icônes des catégories** : on utilise les icônes des couches effectivement. Le plus souvent ils sont dans des cercles, pour "PB Mentaux" on le mettra également dans un cercle.

j'ai également ouvert un ticket our réorganiser le menu de droite et virer ce qui n'est pas vraiment nécessaire .

Merci encore pour tous ces retours et les liens du material design. je n’hésiterai donc pas a te solliciter en cas de problème d'UI haha.

**Comment by overflorian** [comment]
Super ! Très content que tu prennes toutes ces améliorations de l'interface à bras-le-corps.

`tu utilises quelle navigateur stp ?`
la dernière version de Mozilla Firefox sous Ubuntu.

Je reste à ta dispo.

**Comment by TANK2003** [comment]
Okay, j'essaie de regarder ca.

D'ailleurs j'ai résolu et mis en prod le processus de téléchargement des données comme tu l'avais décrit tout en commençant à alléger la plateforme

**Comment by overflorian** [comment]
Hello, ce retour que j'avais fait il y longtemps touchant de nombreux sujets, je vais essayer de les séparer en plusieurs _issues_ :
- https://github.com/data-osm/frontend/issues/46
- https://github.com/data-osm/frontend/issues/47
- https://github.com/data-osm/frontend/issues/48
- https://github.com/data-osm/frontend/issues/49
